{
  "apiVersion": "bitnami.com/v1alpha1",
  "kind": "SealedSecret",
  "metadata": {
    "annotations": {
      "sealedsecrets.bitnami.com/namespace-wide": "true"
    },
    "name": "nalgoo-secret",
    "namespace": "${NAMESPACE}",
    "labels": {
      "app": "${BUILD_REPOSITORY_NAME}",
      "source": "${BUILD_REPOSITORY_NAME}"
    }
  },
  "spec": {
    "encryptedData": {
      "NALGOO_API_KEY": "AgAUQ0jpRAKmH7YLBMZ+4qZj2syfi7rELO1FC6Fr2NRZpMz4j0sbTec4wZxbVgDdGeurwI3Klvhbh7wkoQX+iuDLMJdWixae0wQMgG7tuAwEVoRzYUUs/qCRun7OoD0VMn2KexQfbK+Noa4NzGp4h4Qk8bBp3risPIh2ZUBVA6duL0nPmZD5ANUvTNRi3U7kg/bNhwM+Pln/k9DaJdzt19unUMzZSy9hdMelrrttOD/x7LB6N7HUxA5PYpSazT3APqKgQcjm8our9/WMILqR6wMisakOl3tVZCM+ycYF26dzrBD+fr71WVnNncuaTBwRMNJU+EjTrxKwxGTrvqFAkuZIQRTYFbU8yveUk3RUeH/6LAhdvQI2isIqUtKkQ6wvVzVtuP2cLyODkHVNps7TGgrFn57OXp+WVJZ/XWX6oZPF0h0dd9rr3UHyawtAjTJWM0tNmeGQQEbXbkkH90dwPJ4UNFFnxhoAxWdSMxcUTHUrz70BbrV2BBya04ipAoLUEQNKIm26o0VZmkOJaSGNLvkQ4beIiQEFIHq45SiNWnV8uZiN7QVhsXfYO5UpCw0lAPrZ3tq8n/wQ5IkSltdJDisYujbZi3Eo1Q54xtqiKkWERJMPVIZFf5793hIsLF8ZECYYiV4QMeKYYD9zD11jupcpJbTZXGmpvtoN0co3e/O53cjlHERzH2d6MbVruQgUjYowaPBMCJr8CyIW"
    },
    "template": {
      "metadata": {
        "annotations": {
          "sealedsecrets.bitnami.com/namespace-wide": "true"
        },
        "labels": {
          "app": "${BUILD_REPOSITORY_NAME}",
          "source": "${BUILD_REPOSITORY_NAME}"
        },
        "name": "nalgoo-secret",
        "namespace": "${NAMESPACE}"
      }
    }
  }
}
