resources:
  - deployment.yml
  - service-app.yml
  - ingress.yml
  # Comment-out these lines if no database is used
  - stateful-set.yml
  - stateful-set-meilisearch.yml
  - service-database.yml
  - service-meilisearch.yml
  # Add any secrets here
  #- ./secrets/database.secret.dev.yml
  #- ./secrets/database.secret.staging.yml
  #- ./secrets/database.secret.prod.yml
configurations:
  - configuration.yml

# Keep as is
#namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}
  commit: ${COMMIT}
  tag: ${TAG}
  image: ${IMAGE}

configMapGenerator:
  - name: ${BUILD_REPOSITORY_NAME}-env
    namespace: ${NAMESPACE}
    envs:
      - .env
  - name: ${BUILD_REPOSITORY_NAME}-database
    namespace: ${NAMESPACE}
    envs:
      - .database.env
  - name: ${BUILD_REPOSITORY_NAME}-meilisearch
    namespace: ${NAMESPACE}
    envs:
      - .meilisearch.env
