apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocnapomoc-${BUILD_REPOSITORY_NAME}-ingress
  namespace: ${NAMESPACE}
  labels:
    service: redirect
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-dns01
    cert-manager.io/issue-temporary-certificate: 'true'
    nginx.org/server-snippets: |
      # Skip redirect for ACME HTTP-01 challenge
      if ($request_uri !~ "^/.well-known/acme-challenge/") {
          return 301 https://${BRATISKA_HOSTNAME}/socialne-sluzby-a-byvanie/socialne-sluzby-a-zariadenia/nocna-pomoc;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nocnapomoc.sk
        - www.nocnapomoc.sk
      secretName: nocnapomoc-${BUILD_REPOSITORY_NAME}-tls
  rules:
    - host: nocnapomoc.sk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${BUILD_REPOSITORY_NAME}-app
                port:
                  number: 80
    - host: www.nocnapomoc.sk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${BUILD_REPOSITORY_NAME}-app
                port:
                  number: 80
