{
  "apiVersion": "bitnami.com/v1alpha1",
  "kind": "SealedSecret",
  "metadata": {
    "annotations": {
      "sealedsecrets.bitnami.com/namespace-wide": "true"
    },
    "name": "nalgoo-secret",
    "namespace": "${NAMESPACE}",
    "labels": {
      "app": "${BUILD_REPOSITORY_NAME}",
      "source": "${BUILD_REPOSITORY_NAME}"
    }
  },
  "spec": {
    "encryptedData": {
      "NALGOO_API_KEY": "AgAUaNKAzCzdlMAxaBO7pjJdiuiDG7ueb8yDeV1w/Xe+wLyC1EfJmZnH4IFHSLvs5l6e3v9yKEd9DQLZNRSnusuhQZp2CGclZOzIPZovUv2Lv/1pYyQvdic3otTkgqOk/3Ek4FAY86Z8d9hP0JuRGPBBL1pkRd/lyLaZ0V/7Pwqn1mBKsm9CG2oyxOK6ziZzVsC0sgxsEkRx/DyTMU23pzZ7apckjml02EehWi2QBE0tgeLQHOoq1C46lqbZDEQjPsRhf6MCs15pOzeOZnofwUN3Wp9n3wyYZJlF9VKaEIlo4+W91hgncV3+c0wr7lDir2/v8poEzEb7bifEsUz0wsoesRwqYEPnldFz3GJ7vv90bGd1PUW+SkLZHN/vfHDGwOSfT0zIrtwGUvSRZWRq4TtriRyeqSIpKQ7c5Tez1SJqeo88bJfNlPqUozg+qK45Srd1k5Yn+a5f7kE6/KuWPKjHA9Q72j1achwdqxkDiSA0wtEcjV9zLrwq2QYGnbnVZOOmxJeG+m/PVQ7txGGaAjKMCuAv3t4LXzXpAOnDcO1CK5hsEj49ltHo6UTl7D7KCLcNaQCiehevYfbe2Mha1z86FAfjCtx4Q8+hZgycbc2+l2GmSlVms7b/XVAAPPiJC6JTm5SA7TSUo1zcv2mLEZqt3fripb6/TPvyfn0aSXySc80Q1XJbrHCTCqhpTI07H/eYromTgUidjOfc"
    },
    "template": {
      "metadata": {
        "annotations": {
          "sealedsecrets.bitnami.com/namespace-wide": "true"
        },
        "labels": {
          "app": "${BUILD_REPOSITORY_NAME}",
          "source": "${BUILD_REPOSITORY_NAME}"
        },
        "name": "nalgoo-secret",
        "namespace": "${NAMESPACE}"
      }
    }
  }
}
