apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: bratislava-next-ginis-secret
  namespace: '${NAMESPACE}'
spec:
  encryptedData:
    GINIS_PASSWORD: AgCKNDw/vBO8bUDS7vRM8DurRxfpGZij1+yU4iHYoHmK9ycTBBxCEgQFkZ0ISqxIYW1bbnHQ5Kc+wn+aLDWQn5kJiiN64Db0eAzYCH+GUy7gFSwcAuxn/+ihmlqpFiYbbbP2vjVGqhCvSZnnV2IM8lAylBwNYTT23xlgFPN+CRHqHG0AlpOBKav0KvtidibdNqa8Z0V3nsHNEcNIU40GIqGeFlwamdYuk1Ebbuf4TEhG168Socei/eqWaSQOqPiBnuDY53PhcaKEcKu/Ik6GeFuyFF1Kded2s3TF+M3BibiaWxcE0fKS7cDRzenFlOJ8YUiseE6F+/28crxbaf0YRsyBs/9Ulg2qIVcvuZm+xMDK4h7eU98i08COmEUQb7/aSjF6Ds+yK9psk3So+BAIxXIUsyO0WUMeoDg5Vz3nhbzxKm54DnDhTGrZoCqko6szB2Knzx+eBMAiPfQ761br5Ibx8l/GPoDNWLjg+MukWVX9tpIpE2alHvNDhQ/qsLmvSpFEGsRzS20SynLKYhQeFvZbCQDWVX6jMNVgIDxtFzmmF4yjlNqKxPJdRzJR0A3UU9Inmx8KVv/ucI9JqMBi6zE2Ua1Q8P91q2LlvRJXAqZzwYKu+E6XeEMOQgwEyA9K03YHoq4Nx/wwY/ZxRlgecYAqurMEcPImgdaW2k94H9NGEI914PeCLQLMe/xVyVc4APBiz9c+H3s=
    GINIS_USERNAME: AgByfkT5qdXgFFEaq3kWjk3I9pu1Lp7pn+vqjF2a7LM32a143ww5rqsWh1cVbQ8KXFLtnGHmmbnPxvlIdpplfUXoaL5OWDZig2eSM6hNnSyBcmCinNaTFIdX1UnACLPAmf6w7Gz7VJaGV+D0gNH1fjapAX1f7ElLCzGrJg+Lg51iH6hfh9E45AJV1P4wWmiXDqei9xSw2tidnv/Dalu6QBfP/AI+r5Ij0ZFl9k3STFovD+HxkLMYgg1Ik4e48wPuV4OSzQCoozXc8mBaqr81i52DnRMGsaXRxKOBO2g2UdagZP//TUEZAg4UnbRHqEoQIn++rtYdHrgBwJxNShURPPqfDuF6iny1kYBabCFKvcROglukXsWe0R3yz5X7JnlgisaB1lDh6ZXkCeBwXTipyma3WKFpxCCH25nueVp5GwceVzMEtztG7TCwdMoT0VsR8ojBsO3wN9Qp7CizZ8pwvBhy2yTd37eo1vK/ET+yTpmrfCOEGbD2HJTBXa4uiErE0MwMEgarzvQ/NRwMUwU/O7x4KBop6X7FpGCDnWyyJm0Ol47Fm6Q9yCLgO5hkHlnlo5TnSIAUUN+IXKQo7CKbGOvRY6ybhk4cTv8pSX7fZTD7E0Yma6dSRixS/db8vfHkAJ7NNhxoUd8TOfSz3GNhH7Ktw6yb9uggYpOKx4OGsVfSNCgoFfDz+ZxTwpOGVqoxPJHqBrbbcMaG8ij8x1meK18OILfg
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: '${BUILD_REPOSITORY_NAME}'
        source: '${BUILD_REPOSITORY_NAME}'
      name: bratislava-next-ginis-secret
      namespace: '${NAMESPACE}'
